### PR TITLE
fix: wrong ThenBy and ThenByDesc return types

### PR DESCRIPTION
**Pull request by viceice**
Otherwise we get eslint issues because of the any type.

### CODE REVIEW

**Comment by andrei-markeev** [comment]
I wonder why it was `any` in the first place 😄 
Thanks!

**Comment by viceice** [comment]
Any timeframe when this will be released?

**Comment by andrei-markeev** [comment]
@viceice plan is to do it today. Preparing a bit more changes to include into release.

**Comment by andrei-markeev** [comment]
Published 2.13.0

**Pull request merged**
